// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmcfh4fSJKJROUNuv9GGp47Et1hdfvkko',
    appId: '1:447841275382:web:cfc31f20655f16fbfecbd7',
    messagingSenderId: '447841275382',
    projectId: 'my-mobile-assistant-mp',
    authDomain: 'my-mobile-assistant-mp.firebaseapp.com',
    storageBucket: 'my-mobile-assistant-mp.firebasestorage.app',
    measurementId: 'G-R0NC12N1LY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAC0JOUyW3MCec9QgXz1sZ_t23Nzm11LaA',
    appId: '1:447841275382:android:77357e2fb70ea239fecbd7',
    messagingSenderId: '447841275382',
    projectId: 'my-mobile-assistant-mp',
    storageBucket: 'my-mobile-assistant-mp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQX4dUG5De0hejU7IgeSrfpACq_PU3nwI',
    appId: '1:447841275382:ios:a4ebee46cc028af5fecbd7',
    messagingSenderId: '447841275382',
    projectId: 'my-mobile-assistant-mp',
    storageBucket: 'my-mobile-assistant-mp.firebasestorage.app',
    androidClientId: '447841275382-d3j3sk1ppnlfcdh6uhkcdnqv1thvndtg.apps.googleusercontent.com',
    iosClientId: '447841275382-uvepfpv29gr1ag7psu70j5j3c6b2g49a.apps.googleusercontent.com',
    iosBundleId: 'com.example.untitled3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQX4dUG5De0hejU7IgeSrfpACq_PU3nwI',
    appId: '1:447841275382:ios:a4ebee46cc028af5fecbd7',
    messagingSenderId: '447841275382',
    projectId: 'my-mobile-assistant-mp',
    storageBucket: 'my-mobile-assistant-mp.firebasestorage.app',
    androidClientId: '447841275382-d3j3sk1ppnlfcdh6uhkcdnqv1thvndtg.apps.googleusercontent.com',
    iosClientId: '447841275382-uvepfpv29gr1ag7psu70j5j3c6b2g49a.apps.googleusercontent.com',
    iosBundleId: 'com.example.untitled3',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAmcfh4fSJKJROUNuv9GGp47Et1hdfvkko',
    appId: '1:447841275382:web:33833571a5e6b7e7fecbd7',
    messagingSenderId: '447841275382',
    projectId: 'my-mobile-assistant-mp',
    authDomain: 'my-mobile-assistant-mp.firebaseapp.com',
    storageBucket: 'my-mobile-assistant-mp.firebasestorage.app',
    measurementId: 'G-DHB7WL9BE2',
  );
}
